# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
#  "iPhone 6"
   "iPhone 6 Plus"
#   "iPhone 5",
#   "iPhone 4s"
])

languages([
  "en-US",
  "pt-BR"
])

# The name of the scheme which contains the UI Tests
scheme "ReviewTime"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "./ReviewTime.xcworkspace"

# For more information about all available options run
# snapshot --help
